url: 'https://tech.stanforddaily.com/'
timezone: America/Los_Angeles
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables', 'with_toc_data']
highlighter: rouge
permalink: none
paginate_path: 'page:num'
exclude: ['.gitignore', 'README.md', 'LICENSE.md']
